name: Auto Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate HTML Documentation
      run: |
        python -m pydoc -w src.gravity_flip

    - name: Upload Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: gravity_flip.html







