Resources:
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0453ec754f44f9a4a
      Tags:
        - Key: stage
          Value: production