name: Auto Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate HTML Documentation
      run: |
        python -m pip install --upgrade pip
        for file in $(find src -name '*.py'); do
          module=$(echo $file | sed 's|/|.|g' | sed 's|.py||g' | sed 's|src.||g')
          python -m pydoc -w "src.$module"
        done

    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: "*.html"
